# -*- coding: cp1251 -*-

import re

mail_pattern = re.compile(
	'[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,15}@(mail\.ru|inbox\.ru|bk\.ru|list\.ru|corp\.mail\.ru)$'
)
password_pattern = re.compile('[\040-\176]{4,}$')
number_pattern = re.compile('\+{0,1}[0-9]+$')
upper_ascii_pattern = re.compile('[\200-\377]+')
invalid_chars = re.compile(
	'[\000-\011\013\014\016-\037\202\204-\207\210\211\213\221-\227\230\231\233\271]'
)
RTF_H = '{\\rtf1\\ansi\\ansicpg1251\\deff0\\deflang1049{\\fonttbl{\\f0\\fnil\\fcharset204 Tahoma;}}\r\n{\\colortbl ;\\red0\\green0\\blue0;}\r\n\\viewkind4\\uc1\\pard\\cf1\\f0\\fs18 '
RTF_T = '\\par\r\n}\r\n'

INTRANSTBL = [chr(i) for i in range(0x0,0x09)+range(0x0b,0x0d)+range(0x7f,256)]
OUTTRANSTBL = [hex(ord(i)).replace('0x',"\\'") for i in INTRANSTBL]
INSYMS = ['\\','\r','\n','\t','{','}']
OUTSYMS = ['\\\\','','\\par\r\n','\\tab','\\{','\\}']
'''INSMILES = [
	':)',';)',':-))',';-P','8-)','):-D','}:o)','$-)',
	":-'",'):-(','8-(',":'(",":''()",'S:-o','(:-o','8-0',
	'8-[o]','):-p',':-(','):-$',':-D',':-E',':devil:',':vampire:',
	':-][',':-|','B-j',':~o','(_I_)',':heart:',':-*',':sleepy:',
	':cool:',':viva:',':ok:',':yo:',':suxx:',':think:',':figu:',':kulak:',':fuck:'
]
OUTSMILES = [
	'<###20###img010>','<###20###img011>','<###20###img012>','<###20###img013>',
	'<###20###img014>','<###20###img030>','<###20###img016>','<###20###img017>',
	'<###20###img018>','<###20###img028>','<###20###img020>','<###20###img021>',
	'<###20###img022>','<###20###img023>','<###20###img024>','<###20###img025>',
	'<###20###img026>','<###20###img027>','<###20###img019>','<###20###img029>',
	'<###20###img015>','<###20###img031>','<###20###img032>','<###20###img033>',
	'<###20###img034>','<###20###img035>','<###20###img036>','<###20###img037>',
	'<###20###img038>','<###20###img039>','<###20###img040>','<###20###img041>',
	'<###20###img000>','<###20###img001>','<###20###img002>','<###20###img003>',
	'<###20###img005>','<###20###img006>','<###20###img007>','<###20###img008>',
	'<###20###img009>'
]'''

INSMILES = ["0:)", ":-&", ":&", ":-D", ":D", ":-P", ":P", ":-$", ":$", ":'-(", ":'(",
"%-)", "%)", "B-)", "B)", ":-@", ":@", "B-)", "B)", "(B)", ":-O", ":O", "@};-", "(F)",
"(Y)", ":-*", ":*", ":-$", ":$", ":-)", ":)", "(8)", ":-\"", ":\"", ":-$", ":$", ":-D",
":D", "0:)", ":-(", ":(", ":-?", ":?", ":-O", ":O", ">-)", ">)", ":-)", ":)", ":-\"",
":\"", "|-)", "|)", ";-)", ";)", ":-B", "[:]|||[:]", "{:€", ":-)", ":)", ";-)", ";)",
":-))", ":))", ";-P", ";P", "8-)", "8)", ":-D", ":D", "}:o)", "$-)", "$)", ":-'",
":'", ":-(", ":(", "8-(", "8(", ":'(", ":''()", "S:-o", "S:o", "(:-o", "(:o", "8-0",
"8-[o]", "8[o]", "):-p", "):p", "):-(", "):(", "):-$", "):$", "):-D", "):D", ":-E",
":E", "(6)", "8-x", "8x", ":-][", ":][", ":-|", ":|", "B-j", "Bj", ":~o", "(_I_)",
":-x", ":x", ":-*", ":*", "|-)","|)", "(Y)", ":)>-", "(Y)", ":)>-", ":)>-", "(N)", ":-$",
":$", "*figa*", "=;", "[-(", "[(", "0:)", "(Y)(Y)(Y)", "(X)", "(B)", ":-B", ":B", ":-&",
":&", ":'-(", ":'(", "B-)", "B)", ":-@", ":@", "(C)", ":-@", ":@", ":-&", ":&", "@};-",
"(F)", ":-D", ":D", ":-D:'-(", ":D:'-(", ":-D:'(", ":D:'(", "(E)", ":-L", ":L", ":-*",
":*", ":-x", ":x", "({)", ":-&", ":&", "(R)", ":-$", ":$", ":-(", ":(", "(8)", ":-|",
"|-)", "|)", ":-)", ":)", ":-P", ":P", ":)>-", ":-O", ":O", ":-&", ":&", ":-)", ":)",
">:)", ":-))", ":))", "<):)", ":-@", ":@", ":-O", ":O", ":-P", ":P", "*-:)", "*:)", ":-&",
":&", ":-B", ":B", ":-O", ":O", ":-@", ":@", ":-(", ":(", "B-)", "B)", ":-D", ":D", ";-)",
";)", ":-?", ":?", ":-x", ":x", ":-|", ":|", ":'-(", ":'(", ":'-(", ":'(", "(6)", ":-&",
":&", "%-)", "%)",":-*", ":*", ":-$", ":$", "(X)", "0:)", "8-|", "8|", "(C)", ":-$", ":$",
":-$", ":$"]

OUTSMILES = ["<SMILE>id=400 alt=':Ангелочек:'</SMILE>",
"<SMILE>id=401 alt=':Тошнит:'</SMILE>", 
"<SMILE>id=401alt=':Тошнит:'</SMILE>", 
"<SMILE>id=402 alt=':Улыбка до ушей:'</SMILE>", 
"<SMILE>id=402 alt=':Улыбка до ушей:'</SMILE>", 
"<SMILE>id=403 alt=':Дразнюсь:'</SMILE>", 
"<SMILE>id=403 alt=':Дразнюсь:'</SMILE>", 
"<SMILE>id=404 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=404 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=405 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=405 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=406 alt=':Сумасшествие:'</SMILE>", 
"<SMILE>id=406 alt=':Сумасшествие:'</SMILE>", 
"<SMILE>id=407 alt=':Танцую:'</SMILE>", 
"<SMILE>id=407 alt=':Танцую:'</SMILE>", 
"<SMILE>id=408 alt=':Чертовски злюсь:'</SMILE>",
"<SMILE>id=408 alt=':Чертовски злюсь:'</SMILE>", 
"<SMILE>id=409 alt=':Я круче:'</SMILE>", 
"<SMILE>id=409 alt=':Я круче:'</SMILE>", 
"<SMILE>id=410 alt=':Пиво:'</SMILE>", 
"<SMILE>id=411 alt=':Ты что!:'</SMILE>", 
"<SMILE>id=411 alt=':Ты что!:'</SMILE>", 
"<SMILE>id=412 alt=':Дарю цветочек:'</SMILE>", 
"<SMILE>id=412 alt=':Дарю цветочек:'</SMILE>", 
"<SMILE>id=413 alt=':Ок!:'</SMILE>", 
"<SMILE>id=414 alt=':Целую:'</SMILE>", 
"<SMILE>id=414 alt=':Целую:'</SMILE>", 
"<SMILE>id=415 alt=':Поцеловали:'</SMILE>", 
"<SMILE>id=415 alt=':Поцеловали:'</SMILE>", 
"<SMILE>id=416 alt=':Хихикаю:'</SMILE>", 
"<SMILE>id=416 alt=':Хихикаю:'</SMILE>", 
"<SMILE>id=417 alt=':Слушаю музыку:'</SMILE>", 
"<SMILE>id=418 alt=':Не-а:'</SMILE>", 
"<SMILE>id=418 alt=':Не-а:'</SMILE>", 
"<SMILE>id=419 alt=':Извини:'</SMILE>", 
"<SMILE>id=419 alt=':Извини:'</SMILE>", 
"<SMILE>id=420 alt=':Лопну от смеха:'</SMILE>", 
"<SMILE>id=420 alt=':Лопну от смеха:'</SMILE>", 
"<SMILE>id=421 alt=':Мечтаю:'</SMILE>", 
"<SMILE>id=422 alt=':В печали:'</SMILE>", 
"<SMILE>id=422 alt=':В печали:'</SMILE>", 
"<SMILE>id=423 alt=':Надо подумать:'</SMILE>", 
"<SMILE>id=423 alt=':Надо подумать:'</SMILE>", 
"<SMILE>id=424 alt=':Ой, ё:'</SMILE>", 
"<SMILE>id=424 alt=':Ой, ё:'</SMILE>", 
"<SMILE>id=425 alt=':Кричу:'</SMILE>", 
"<SMILE>id=425 alt=':Кричу:'</SMILE>", 
"<SMILE>id=426 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=426 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=427 alt=':Не знаю:'</SMILE>", 
"<SMILE>id=427 alt=':Не знаю:'</SMILE>", 
"<SMILE>id=428 alt=':В изнеможении:'</SMILE>", 
"<SMILE>id=428 alt=':В изнеможении:'</SMILE>", 
"<SMILE>id=429 alt=':Подмигиваю:'</SMILE>", 
"<SMILE>id=429 alt=':Подмигиваю:'</SMILE>", 
"<SMILE>id=430 alt=':Уррра!:'</SMILE>", 
"<SMILE>id=431 alt=':Бойан:'</SMILE>", 
"<SMILE>id=432 alt=':Ктулху:'</SMILE>", 
"<###20###img010>", "<###20###img010>", "<###20###img011>", "<###20###img011>",
"<###20###img012>", "<###20###img012>", "<###20###img013>", "<###20###img013>",
"<###20###img014>", "<###20###img014>", "<###20###img015>", "<###20###img015>",
"<###20###img016>", "<###20###img017>", "<###20###img017>", "<###20###img018>",
"<###20###img018>", "<###20###img019>", "<###20###img019>", "<###20###img020>", 
"<###20###img020>", "<###20###img021>", "<###20###img022>", "<###20###img023>", 
"<###20###img023>", "<###20###img024>", "<###20###img024>", "<###20###img025>", 
"<###20###img026>", "<###20###img026>", "<###20###img027>", "<###20###img027>", 
"<###20###img028>", "<###20###img028>","<###20###img029>", "<###20###img029>", 
"<###20###img030>", "<###20###img030>", "<###20###img031>", "<###20###img031>", 
"<###20###img032>", "<###20###img033>", "<###20###img033>", "<###20###img034>", 
"<###20###img034>", "<###20###img035>", "<###20###img035>", "<###20###img036>", 
"<###20###img036>", "<###20###img037>", "<###20###img038>", "<###20###img039>", 
"<###20###img039>", "<###20###img040>", "<###20###img040>", "<###20###img041>", 
"<###20###img041>", "<###20###img000>", "<###20###img001>", "<###20###img002>", 
"<###20###img003>", "<###20###img004>", "<###20###img005>", "<###20###img006>", 
"<###20###img006>", "<###20###img007>", "<###20###img008>", "<###20###img009>", 
"<###20###img009>", "<SMILE>id=200 alt=':Ангелочек:'</SMILE>",
"<SMILE>id=201 alt=':Аплодисменты:'</SMILE>", 
"<SMILE>id=202 alt=':Красотка:'</SMILE>", 
"<SMILE>id=203 alt=':Пиво:'</SMILE>", 
"<SMILE>id=204 alt=':Читаю:'</SMILE>", 
"<SMILE>id=204 alt=':Читаю:'</SMILE>", 
"<SMILE>id=205 alt=':Мёрзну:'</SMILE>", 
"<SMILE>id=205 alt=':Мёрзну:'</SMILE>", 
"<SMILE>id=206 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=206 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=207 alt=':Танцую:'</SMILE>", 
"<SMILE>id=207 alt=':Танцую:'</SMILE>", 
"<SMILE>id=208 alt=':Чертовски злюсь:'</SMILE>", 
"<SMILE>id=208 alt=':Чертовски злюсь:'</SMILE>", 
"<SMILE>id=209 alt=':Жую:'</SMILE>", 
"<SMILE>id=210 alt=':Побью:'</SMILE>", 
"<SMILE>id=210 alt=':Побью:'</SMILE>", 
"<SMILE>id=211 alt=':Побили:'</SMILE>", 
"<SMILE>id=211 alt=':Побили:'</SMILE>", 
"<SMILE>id=212 alt=':Дарю цветочек:'</SMILE>", 
"<SMILE>id=212 alt=':Дарю цветочек:'</SMILE>", 
"<SMILE>id=213 alt=':Смеюсь:'</SMILE>", 
"<SMILE>id=213 alt=':Смеюсь:'</SMILE>", 
"<SMILE>id=214 alt=':Смеюсь и плачу:'</SMILE>", 
"<SMILE>id=214 alt=':Смеюсь и плачу:'</SMILE>", 
"<SMILE>id=214 alt=':Смеюсь и плачу:'</SMILE>", 
"<SMILE>id=214 alt=':Смеюсь и плачу:'</SMILE>", 
"<SMILE>id=215 alt=':Подарок:'</SMILE>", 
"<SMILE>id=216 alt=':Ворчу:'</SMILE>", 
"<SMILE>id=216 alt=':Ворчу:'</SMILE>", 
"<SMILE>id=217 alt=':Целую:'</SMILE>", 
"<SMILE>id=217 alt=':Целую:'</SMILE>", 
"<SMILE>id=218 alt=':Люблю:'</SMILE>", 
"<SMILE>id=218 alt=':Люблю:'</SMILE>", 
"<SMILE>id=219 alt=':Застрелю:'</SMILE>", 
"<SMILE>id=220 alt=':Выпей яду:'</SMILE>", 
"<SMILE>id=220 alt=':Выпей яду:'</SMILE>", 
"<SMILE>id=221 alt=':Лучезарно:'</SMILE>", 
"<SMILE>id=222 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=222 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=223 alt=':Расстраиваюсь:'</SMILE>", 
"<SMILE>id=223 alt=':Расстраиваюсь:'</SMILE>", 
"<SMILE>id=224 alt=':Пою:'</SMILE>", 
"<SMILE>id=225 alt=':Скучаю:'</SMILE>", 
"<SMILE>id=226 alt=':Засыпаю:'</SMILE>", 
"<SMILE>id=226 alt=':Засыпаю:'</SMILE>", 
"<SMILE>id=227 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=227 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=228 alt=':Показываю язык:'</SMILE>", 
"<SMILE>id=228 alt=':Показываю язык:'</SMILE>", 
"<SMILE>id=229 alt=':Peace!:'</SMILE>", 
"<SMILE>id=230 alt=':Удивляюсь:'</SMILE>", 
"<SMILE>id=230 alt=':Удивляюсь:'</SMILE>", 
"<SMILE>id=231 alt=':Тошнит:'</SMILE>", 
"<SMILE>id=231 alt=':Тошнит:'</SMILE>", 
"<SMILE>id=300 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=300 alt=':Улыбаюсь:'</SMILE>", 
"<SMILE>id=301 alt=':Злорадствую:'</SMILE>", 
"<SMILE>id=302 alt=':Радуюсь:'</SMILE>", 
"<SMILE>id=302 alt=':Радуюсь:'</SMILE>", 
"<SMILE>id=303 alt=':Старичок:'</SMILE>", 
"<SMILE>id=304 alt=':Свирепствую:'</SMILE>", 
"<SMILE>id=304 alt=':Свирепствую:'</SMILE>", 
"<SMILE>id=305 alt=':Пугаюсь:'</SMILE>", 
"<SMILE>id=305 alt=':Пугаюсь:'</SMILE>", 
"<SMILE>id=306 alt=':Показываю язык:'</SMILE>", 
"<SMILE>id=306 alt=':Показываю язык:'</SMILE>", 
"<SMILE>id=307 alt=':Умник:'</SMILE>", 
"<SMILE>id=307 alt=':Умник:'</SMILE>", 
"<SMILE>id=308 alt=':Алкоголик:'</SMILE>", 
"<SMILE>id=308 alt=':Алкоголик:'</SMILE>", 
"<SMILE>id=309 alt=':Вояка:'</SMILE>", 
"<SMILE>id=309 alt=':Вояка:'</SMILE>", 
"<SMILE>id=310 alt=':Удивляюсь:'</SMILE>", 
"<SMILE>id=310 alt=':Удивляюсь:'</SMILE>", 
"<SMILE>id=311 alt=':Чертовски злюсь:'</SMILE>", 
"<SMILE>id=311 alt=':Чертовски злюсь:'</SMILE>", 
"<SMILE>id=312 alt=':Расстраиваюсь:'</SMILE>", 
"<SMILE>id=312 alt=':Расстраиваюсь:'</SMILE>", 
"<SMILE>id=313 alt=':Панк:'</SMILE>", 
"<SMILE>id=313 alt=':Панк:'</SMILE>", 
"<SMILE>id=314 alt=':Лопну от смеха:'</SMILE>", 
"<SMILE>id=314 alt=':Лопну от смеха:'</SMILE>", 
"<SMILE>id=315 alt=':Подмигиваю:'</SMILE>", 
"<SMILE>id=315 alt=':Подмигиваю:'</SMILE>", 
"<SMILE>id=316 alt=':Думаю:'</SMILE>", 
"<SMILE>id=316 alt=':Думаю:'</SMILE>", 
"<SMILE>id=317 alt=':Люблю:'</SMILE>", 
"<SMILE>id=317 alt=':Люблю:'</SMILE>", 
"<SMILE>id=318 alt=':Подавлен:'</SMILE>", 
"<SMILE>id=318 alt=':Подавлен:'</SMILE>", 
"<SMILE>id=319 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=319 alt=':Рыдаю:'</SMILE>", 
"<SMILE>id=320 alt=':Сейчас расплачусь:'</SMILE>", 
"<SMILE>id=320 alt=':Сейчас расплачусь:'</SMILE>", 
"<SMILE>id=321 alt=':Злюсь:'</SMILE>", 
"<SMILE>id=322 alt=':Тошнит:'</SMILE>", 
"<SMILE>id=322 alt=':Тошнит:'</SMILE>", 
"<SMILE>id=323 alt=':Сумасшествие:'</SMILE>", 
"<SMILE>id=323 alt=':Сумасшествие:'</SMILE>", 
"<SMILE>id=324 alt=':Целую:'</SMILE>", 
"<SMILE>id=324 alt=':Целую:'</SMILE>", 
"<SMILE>id=325 alt=':Поцеловали:'</SMILE>", 
"<SMILE>id=325 alt=':Поцеловали:'</SMILE>", 
"<SMILE>id=326 alt=':Красотка:'</SMILE>", 
"<SMILE>id=327 alt=':Ангелочек:'</SMILE>", 
"<SMILE>id=328 alt=':Подозрительно:'</SMILE>", 
"<SMILE>id=328 alt=':Подозрительно:'</SMILE>", 
"<SMILE>id=329 alt=':Жую:'</SMILE>", 
"<SMILE>id=330 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=330 alt=':Смущаюсь:'</SMILE>", 
"<SMILE>id=331 alt=':Стыдно:'</SMILE>", 
"<SMILE>id=331 alt=':Стыдно:'</SMILE>"]

INCHARS = tuple(INSYMS+INTRANSTBL+INSMILES)
OUTCHARS = tuple(OUTSYMS+OUTTRANSTBL+OUTSMILES)

IN_TRANSLIT_TBL = tuple(["'",chr(0xa8),chr(0xb8)] + [chr(i) for i in range(0xc0,256)])
_lat = [
	'a','b','v','g','d','e','zh','z','i','jj','k','l','m','n','o','p','r',
	's','t','u','f','kh','c','ch','sh','shh','"','y',"'",'eh','yu','ya'
]
OUT_TRANSLIT_TBL = tuple(['*','Jo','jo'] + [x[0].upper()+x[1:] for x in _lat] + _lat)

UPPER_ASCII = tuple([chr(i) for i in range(128,256)])
NULL_ASCII = tuple(['' for i in range(128,256)])
